apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wil-app
  name: wil-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil-app
  strategy: {}
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.10
        name: wil-app
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: MESSAGE
            value: "Hello from app1"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wil-app-service
spec:
  selector:
    app: wil-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-app-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: wil-app-service
            port:
              name: http
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
